In [1]:
from datetime import datetime

import numpy as np
import pandas as pd
import rasterio as rio
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
import geopandas as gpd
from concurrent.futures import ThreadPoolExecutor

In [2]:
MODEL_NAME = f"XGB_v1_{datetime.now().timestamp()}"
MODEL_NAME

'XGB_v1_1787083166.71639'

In [15]:
DATA_PREFIX = "../data"
OUTPUT_PREFIX = "../output"

TRAIN_PARQUET = f"{OUTPUT_PREFIX}/train_only_biomass.parquet"
TEST_PARQUET = f"{OUTPUT_PREFIX}/test_only_biomass.parquet"
SUBMISSION_CSV = f"{DATA_PREFIX}/sample_submission.csv"

In [4]:
PREDICTORS = ["agb"]

LABEL = "biomass"

In [5]:
train_df = gpd.read_parquet(TRAIN_PARQUET)
train_df

,x,y,year,biomass,tile_id,geometry
0,3137124.7416963745,1810803.9191588927,2020,28.742064,038052,POINT (-3.54712 38.43217)
1,3138084.7416963745,1808543.9191588927,2020,61.379017,038052,POINT (-3.53221 38.41357)
2,3136834.7416963745,1809903.9191588927,2020,41.445705,038052,POINT (-3.54874 38.42368)
3,3137594.7416963745,1810823.9191588927,2020,25.911734,038052,POINT (-3.54186 38.4331)
4,3137914.7416963745,1808923.9191588927,2020,40.892021,038052,POINT (-3.53481 38.41668)
...,...,...,...,...,...,...
5165029,3111664.7416963745,2243933.9191588927,2019,58.634174,035805,POINT (-4.70534 42.23312)
5165030,3111624.7416963745,2243883.9191588927,2019,60.487827,035805,POINT (-4.70571 42.23261)
5165031,3113104.7416963745,2243803.9191588927,2019,118.166924,035805,POINT (-4.68791 42.2345)
5165032,3113074.7416963745,2243833.9191588927,2019,104.021767,035805,POINT (-4.68834 42.23471)
5165033,3111394.7416963745,2245373.9191588927,2019,16.892933,035805,POINT (-4.71171 42.24537)

In [6]:
tile_ids = train_df["tile_id"].unique()

def run_per_tile(tile_id):
    tile_sample = train_df[train_df["tile_id"] == tile_id]
    coords = [coord for coord in zip(tile_sample.geometry.x, tile_sample.geometry.y)]
    years = tile_sample["year"].unique()

    for year in years:
        print(f"Run {tile_id} {year}")
        with rio.open(
            f"https://storage.googleapis.com/gee-ramiqcom-s4g-bucket/opengeohub_summerschool_2026/ctrees_biomass/tile_{tile_id}_{year}.tif"
        ) as src:
            train_df.loc[
                (train_df["tile_id"] == tile_id) & (train_df["year"] == year), "agb"
            ] = [data for data in src.sample(coords)]

with ThreadPoolExecutor(8) as executor:
    jobs = []
    for tile_id in tile_ids:
        jobs.append(executor.submit(run_per_tile, tile_id))
    for job in jobs:
        try:
            job.result()
        except Exception as e:
            print(f"Error: {e}")

train_df

Run 036385 2019
Run 026261 2021
Run 030430 2019
Run 039974 2019
Run 086895 2016
Run 051927 2019
Run 038052 2020
Run 038510 2019
Run 045997 2019
Run 088988 2016
Run 085676 2016
Run 034493 2019
Run 040151 2019
Run 083291 2016
Run 029528 2019
Run 034594 2019
Run 042237 2019
Run 045356 2019
Run 045312 2019
Run 026863 2021
Run 092872 2016
Run 041342 2019
Run 041182 2019
Run 098252 2016
Run 051637 2019
Run 040307 2019
Run 061154 2020
Run 045647 2019
Run 044463 2019
Run 027166 2021
Run 035985 2019
Run 052828 2019
Run 028643 2021
Run 077292 2016
Run 040578 2019
Run 027461 2021
Run 074300 2016
Run 086897 2016
Run 042360 2019
Run 089569 2016
Run 090471 2016
Run 096461 2016
Run 043592 2019
Run 028651 2021
Run 037013 2019
Run 093165 2016
Run 088705 2016
Run 093179 2016
Run 038493 2019
Run 044421 2019
Run 038501 2019
Run 061122 2020
Run 086583 2016
Run 048900 2019
Run 048617 2019
Run 046294 2019
Run 030599 2019
Run 059035 2020
Run 050431 2019
Run 059655 2020
Run 086276 2016
Run 088963 2016
Run 036404 2019
Run 029985 2019
Run 090484 2016
Run 019880 2018
Run 026848 2021
Run 027616 2019
Run 039848 2019
Run 042660 2019
Run 063545 2020
Run 032672 2019
Run 032226 2021
Run 035373 2019
Run 042381 2019
Run 028932 2021
Run 047414 2019
Run 075809 2016
Run 028064 2020
Run 083595 2016
Run 094679 2016
Run 031793 2019
Run 040282 2019
Run 046185 2019
Run 073999 2016
Run 059951 2020
Run 085075 2016
Run 045625 2019
Run 050698 2019
Run 021108 2019
Run 088668 2016
Run 097064 2016
Run 030309 2019
Run 059040 2020
Run 061127 2020
Run 028213 2019
Run 031482 2019
Run 088666 2016
Run 096756 2016
Run 045319 2019
Run 028631 2021
Run 044496 2019
Run 073997 2016
Run 093465 2016
Run 091364 2016
Run 086871 2016
Run 028344 2021
Run 027437 2021
Run 033867 2019
Run 095557 2016
Run 028515 2019
Run 035690 2019
Run 038212 2019
Run 048012 2019
Run 093769 2016
Run 031179 2019
Run 089580 2016
Run 044633 2019
Run 097075 2016
Run 030434 2021
Run 041946 2019
Run 030150 2021
Run 078190 2016
Run 044998 2019
Run 058751 2020
Run 031201 2019
Run 026412 2019
Run 028812 2019
Run 046889 2019
Run 051928 2019
Run 032671 2020
Run 035096 2019
Run 076991 2016
Run 051933 2019
Run 034944 2020
Run 080592 2016
Run 045596 2019
Run 054327 2019
Run 081788 2016
Run 083890 2016
Run 040610 2019
Run 098563 2016
Run 039089 2019
Run 044494 2019
Run 029712 2019
Run 057854 2020
Run 095571 2016
Run 085979 2016
Run 049192 2019
Run 035802 2019
Run 029411 2019
Run 074000 2016
Run 046858 2019
Run 034782 2019
Run 081493 2016
Run 030725 2019
Run 038969 2019
Run 062651 2020
Run 095575 2016
Run 096763 2016
Run 033598 2019
Run 026567 2021
Run 043296 2019
Run 042074 2019
Run 042085 2019
Run 039267 2019
Run 047119 2019
Run 036108 2019
Run 045313 2019
Run 021386 2018
Run 028941 2021
Run 062632 2020
Run 029555 2021
Run 045664 2019
Run 025959 2021
Run 031777 2019
Run 035835 2019
Run 035805 2019

,x,y,year,biomass,tile_id,geometry,agb
0,3137124.7416963745,1810803.9191588927,2020,28.742064,038052,POINT (-3.54712 38.43217),10.400000
1,3138084.7416963745,1808543.9191588927,2020,61.379017,038052,POINT (-3.53221 38.41357),3.500000
2,3136834.7416963745,1809903.9191588927,2020,41.445705,038052,POINT (-3.54874 38.42368),17.799999
3,3137594.7416963745,1810823.9191588927,2020,25.911734,038052,POINT (-3.54186 38.4331),3.200000
4,3137914.7416963745,1808923.9191588927,2020,40.892021,038052,POINT (-3.53481 38.41668),17.100000
...,...,...,...,...,...,...,...
5165029,3111664.7416963745,2243933.9191588927,2019,58.634174,035805,POINT (-4.70534 42.23312),8.700000
5165030,3111624.7416963745,2243883.9191588927,2019,60.487827,035805,POINT (-4.70571 42.23261),3.800000
5165031,3113104.7416963745,2243803.9191588927,2019,118.166924,035805,POINT (-4.68791 42.2345),0.500000
5165032,3113074.7416963745,2243833.9191588927,2019,104.021767,035805,POINT (-4.68834 42.23471),0.800000
5165033,3111394.7416963745,2245373.9191588927,2019,16.892933,035805,POINT (-4.71171 42.24537),4.800000

In [7]:
# split train and test data
train, test = train_test_split(train_df, test_size=0.3)

In [8]:
MODEL_NAME = f"XGB_v1_{datetime.now().timestamp()}"
model = XGBRegressor(n_estimators=500)
model.fit(train[PREDICTORS], train[LABEL])

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=500,
             n_jobs=None, num_parallel_tree=None, ...)

In [9]:
total = sum(model.feature_importances_)
print("Feature importance")
pd.Series(dict(zip(model.feature_names_in_, model.feature_importances_ / total * 100)))

Feature importance

agb    100.0
dtype: float32

In [10]:
test_apply = model.predict(test[PREDICTORS])
r2 = np.corrcoef(test[LABEL], test_apply)[0, 1] ** 2
mae = mean_absolute_error(test[LABEL], test_apply)
print(f"R^2={r2}", f"MAE={mae}")

R^2=0.30389214698191214 MAE=31.56534286460224

In [16]:
test_df = gpd.read_parquet(TEST_PARQUET)
test_df

,row_id,tile_id,x,y,year,geometry
0,028631_3040064_2251003,028631,3040064.7416963745,2251003.9191588927,2021,POINT (-5.57242 42.1662)
1,028631_3041214_2252063,028631,3041214.7416963745,2252063.9191588927,2021,POINT (-5.56121 42.17768)
2,028631_3041184_2251693,028631,3041184.7416963745,2251693.9191588927,2021,POINT (-5.56071 42.17436)
3,028631_3039864_2250783,028631,3039864.7416963745,2250783.9191588927,2021,POINT (-5.57428 42.16389)
4,028631_3040224_2251483,028631,3040224.7416963745,2251483.9191588927,2021,POINT (-5.57163 42.17073)
...,...,...,...,...,...,...
45014,061751_3374644_2043173,061751,3374644.7416963745,2043173.9191588927,2020,POINT (-1.21909 40.85472)
45015,061751_3374594_2043203,061751,3374594.7416963745,2043203.9191588927,2020,POINT (-1.21972 40.85492)
45016,061751_3374624_2043173,061751,3374624.7416963745,2043173.9191588927,2020,POINT (-1.21932 40.85469)
45017,061751_3374614_2043223,061751,3374614.7416963745,2043223.9191588927,2020,POINT (-1.21952 40.85512)
45018,061751_3374654_2043203,061751,3374654.7416963745,2043203.9191588927,2020,POINT (-1.21902 40.855)

In [61]:
submission_df = pd.read_csv(SUBMISSION_CSV)
submission_df

                           Id  Expected
0      028631_3040064_2251003       0.0
1      028631_3041214_2252063       0.0
2      028631_3041184_2251693       0.0
3      028631_3039864_2250783       0.0
4      028631_3040224_2251483       0.0
...                       ...       ...
45014  061751_3374644_2043173       0.0
45015  061751_3374594_2043203       0.0
45016  061751_3374624_2043173       0.0
45017  061751_3374614_2043223       0.0
45018  061751_3374654_2043203       0.0

[45019 rows x 2 columns]

In [64]:
submission_df.loc[test_df_mask, "Expected"] = model.predict(test_df[NEW_PREDICTORS])
submission_df.loc[~test_df_mask, "Expected"] = 0
submission_df

                           Id    Expected
0      028631_3040064_2251003  216.954559
1      028631_3041214_2252063  215.189774
2      028631_3041184_2251693  257.339050
3      028631_3039864_2250783  218.816223
4      028631_3040224_2251483  239.833191
...                       ...         ...
45014  061751_3374644_2043173   49.675964
45015  061751_3374594_2043203   45.027897
45016  061751_3374624_2043173   87.220787
45017  061751_3374614_2043223  136.897537
45018  061751_3374654_2043203   70.820763

[45019 rows x 2 columns]

In [65]:
RESULT_CSV = f"{OUTPUT_PREFIX}/results_{MODEL_NAME}.csv"
submission_df.to_csv(RESULT_CSV, index=False)

MODEL_NAME

'XGB_v1_1787050491.38527'