In [6]:
import pandas as pd
from xgboost import XGBRFRegressor, XGBRegressor
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
from datetime import datetime
import rasterio as rio
from sklearn.linear_model import LinearRegression

In [2]:
MODEL_NAME = f"XGB_v1_{datetime.now().timestamp()}"
MODEL_NAME

'XGB_v1_1787082376.589315'

In [3]:
DATA_PREFIX = "../data"
OUTPUT_PREFIX = "../output"

TRAIN_PARQUET = f"{OUTPUT_PREFIX}/train_only_biomass.parquet"
TEST_CSV = f"{DATA_PREFIX}/test_only_biomass.csv"
SUBMISSION_CSV = f"{DATA_PREFIX}/sample_submission.csv"

In [4]:
PREDICTORS = [
    "agb"
]

LABEL = "biomass"

In [5]:
train_df = pd.read_parquet(TRAIN_PARQUET)
train_df

,x,y,year,biomass,tile_id,geometry,geometry_bbox
0,3137124.7416963745,1810803.9191588927,2020,28.742064,038052,b'\x01\x01\x00\x00\x00\xd3\xac\xa8\x13~`\x0c\x...,"{'xmin': -3.5471155643463135, 'ymin': 38.43216..."
1,3138084.7416963745,1808543.9191588927,2020,61.379017,038052,b'\x01\x01\x00\x00\x00\x0b2\xa0\xef\xf8A\x0c\x...,"{'xmin': -3.5322134494781494, 'ymin': 38.41356..."
2,3136834.7416963745,1809903.9191588927,2020,41.445705,038052,b'\x01\x01\x00\x00\x00#\x8fOS\xd4c\x0c\xc0Vz\x...,"{'xmin': -3.5487449169158936, 'ymin': 38.42367..."
3,3137594.7416963745,1810823.9191588927,2020,25.911734,038052,b'\x01\x01\x00\x00\x00$\xa9\xd5\xfe\xbbU\x0c\x...,"{'xmin': -3.5418624877929688, 'ymin': 38.43309..."
4,3137914.7416963745,1808923.9191588927,2020,40.892021,038052,"b""\x01\x01\x00\x00\x00\x1a'\x1d\xf3LG\x0c\xc0f...","{'xmin': -3.5348148345947266, 'ymin': 38.41667..."
...,...,...,...,...,...,...,...
5165029,3111664.7416963745,2243933.9191588927,2019,58.634174,035805,b'\x01\x01\x00\x00\x00\x1d\xf5\xdb\xe8D\xd2\x1...,"{'xmin': -4.705341339111328, 'ymin': 42.233116..."
5165030,3111624.7416963745,2243883.9191588927,2019,60.487827,035805,b'\x01\x01\x00\x00\x00\xe0&\xea\x13\xa5\xd2\x1...,"{'xmin': -4.705708026885986, 'ymin': 42.232601..."
5165031,3113104.7416963745,2243803.9191588927,2019,118.166924,035805,b'\x01\x01\x00\x00\x00\xdbb\x1b\x8dl\xc0\x12\x...,"{'xmin': -4.687914848327637, 'ymin': 42.234489..."
5165032,3113074.7416963745,2243833.9191588927,2019,104.021767,035805,b'\x01\x01\x00\x00\x00h\x7f#Z\xdb\xc0\x12\xc0\...,"{'xmin': -4.6883368492126465, 'ymin': 42.23470..."
5165033,3111394.7416963745,2245373.9191588927,2019,16.892933,035805,b'\x01\x01\x00\x00\x00\xa2\xa1=<\xc9\xd8\x12\x...,"{'xmin': -4.711705207824707, 'ymin': 42.245372..."

In [ ]:
tile_ids = train_df["tile_id"].unique()

for tile_id in tile_ids:
  tile_sample = train_df[train_df["tile_id"] == tile_id]
  years = tile_sample["years"].unique()
  for year in years:
    with rio.open(f"")

In [55]:
# split train and test data
train, test = train_test_split(train_df, test_size=0.3)

In [56]:
MODEL_NAME = f"XGB_v1_{datetime.now().timestamp()}"
model = XGBRegressor(n_estimators=500)
model.fit(train[NEW_PREDICTORS], train[LABEL])

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=500,
             n_jobs=None, num_parallel_tree=None, ...)

In [57]:
total = sum(model.feature_importances_)
print("Feature importance")
pd.Series(dict(zip(model.feature_names_in_, model.feature_importances_ / total * 100)))

Feature importance

b02_s2.cdse.quarterly_xxxx0401_xxxx0631     3.701432
b04_s2.cdse.quarterly_xxxx0401_xxxx0631    38.018887
b08_s2.cdse.quarterly_xxxx0401_xxxx0631     1.198782
obs_s2.cdse.quarterly_xxxx0401_xxxx0631     5.371201
HH_dB_palsar_xxxx                           4.182187
HV_dB_palsar_xxxx                          15.130033
angle_palsar_xxxx                           1.712677
vv.sentinel1_xxxx07                         1.640134
vh.sentinel1_xxxx07                         1.839339
bioregion                                   6.145675
forest_type                                 5.778750
NDWI                                        1.637150
NDVI                                        7.866502
RVI_PALSAR                                  0.600012
RVI_S1                                      5.177240
dtype: float32

In [58]:
test_apply = model.predict(test[NEW_PREDICTORS])
r2 = np.corrcoef(test[LABEL], test_apply)[0, 1] ** 2
mae = mean_absolute_error(test[LABEL], test_apply)
print(f"R^2={r2}", f"MAE={mae}")

R^2=0.6535289928318548 MAE=20.992383595418747

In [59]:
test_df = pd.read_csv(TEST_CSV)
test_df

,Unnamed: 0,row_id,x,y,b02_s2.cdse.quarterly_xxxx0401_xxxx0631,b04_s2.cdse.quarterly_xxxx0401_xxxx0631,b08_s2.cdse.quarterly_xxxx0401_xxxx0631,obs_s2.cdse.quarterly_xxxx0401_xxxx0631,HH_dB_palsar_xxxx,HV_dB_palsar_xxxx,angle_palsar_xxxx,qa_palsar_xxxx,vv.sentinel1_xxxx07,vh.sentinel1_xxxx07,bioregion,forest_type,year,tile_id
0,24,028631_3040064_2251003,3.040065e+06,2.251004e+06,100.0,103.0,2788.0,21.0,-10.144670,-13.913869,62.935490,255.0,4345.0,1192.0,9.0,9.0,2021,28631
1,30,028631_3041214_2252063,3.041215e+06,2.252064e+06,171.0,208.0,2746.0,20.0,-7.349724,-10.590984,42.061958,255.0,1360.0,335.0,9.0,9.0,2021,28631
2,33,028631_3041184_2251693,3.041185e+06,2.251694e+06,98.0,91.0,3664.0,21.0,-6.874915,-12.238380,41.123703,255.0,2078.0,615.0,9.0,9.0,2021,28631
3,38,028631_3039864_2250783,3.039865e+06,2.250784e+06,98.0,131.0,3060.0,20.0,-5.991528,-10.575653,52.339672,255.0,2116.0,548.0,9.0,9.0,2021,28631
4,64,028631_3040224_2251483,3.040225e+06,2.251484e+06,72.0,88.0,3772.0,22.0,-6.046557,-10.341457,48.277470,255.0,2367.0,385.0,9.0,9.0,2021,28631
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45014,884113,061751_3374644_2043173,3.374645e+06,2.043174e+06,287.0,323.0,4392.0,17.0,-9.803984,-15.310058,37.016045,255.0,1363.0,397.0,9.0,9.0,2020,61751
45015,885387,061751_3374594_2043203,3.374595e+06,2.043204e+06,608.0,922.0,3732.0,17.0,-11.813272,-15.730301,38.029926,255.0,1387.0,277.0,9.0,0.0,2020,61751
45016,890670,061751_3374624_2043173,3.374625e+06,2.043174e+06,212.0,268.0,3086.0,17.0,-11.729067,-16.882254,36.219688,255.0,1336.0,308.0,9.0,9.0,2020,61751
45017,895641,061751_3374614_2043223,3.374615e+06,2.043224e+06,153.0,215.0,3280.0,17.0,-7.831328,-13.507510,35.155594,255.0,2629.0,603.0,9.0,0.0,2020,61751
45018,897503,061751_3374654_2043203,3.374655e+06,2.043204e+06,192.0,252.0,3808.0,17.0,-6.234363,-12.168104,35.301659,255.0,1510.0,448.0,9.0,0.0,2020,61751

In [60]:
test_df["NDVI"] = (
    (
        train_df["b08_s2.cdse.quarterly_xxxx0401_xxxx0631"]
        - train_df["b04_s2.cdse.quarterly_xxxx0401_xxxx0631"]
    )
    * (
        train_df["b08_s2.cdse.quarterly_xxxx0401_xxxx0631"]
        + train_df["b04_s2.cdse.quarterly_xxxx0401_xxxx0631"]
    )
    * 1e4
)

test_df["NDWI"] = (
    (
        train_df["b02_s2.cdse.quarterly_xxxx0401_xxxx0631"]
        - train_df["b08_s2.cdse.quarterly_xxxx0401_xxxx0631"]
    )
    * (
        train_df["b02_s2.cdse.quarterly_xxxx0401_xxxx0631"]
        + train_df["b08_s2.cdse.quarterly_xxxx0401_xxxx0631"]
    )
    * 1e4
)

test_df["RVI_PALSAR"] = (
    (train_df["HH_dB_palsar_xxxx"] - train_df["HV_dB_palsar_xxxx"])
    * (train_df["HH_dB_palsar_xxxx"] + train_df["HV_dB_palsar_xxxx"])
    * 1e4
)

test_df["RVI_S1"] = (
    (train_df["vv.sentinel1_xxxx07"] - train_df["vh.sentinel1_xxxx07"])
    * (train_df["vv.sentinel1_xxxx07"] + train_df["vh.sentinel1_xxxx07"])
    * 1e4
)

test_df_mask = (test_df["NDVI"] > 3000) & (test_df["NDWI"] <= 0)
test_df = test_df[test_df_mask]

In [61]:
submission_df = pd.read_csv(SUBMISSION_CSV)
submission_df

                           Id  Expected
0      028631_3040064_2251003       0.0
1      028631_3041214_2252063       0.0
2      028631_3041184_2251693       0.0
3      028631_3039864_2250783       0.0
4      028631_3040224_2251483       0.0
...                       ...       ...
45014  061751_3374644_2043173       0.0
45015  061751_3374594_2043203       0.0
45016  061751_3374624_2043173       0.0
45017  061751_3374614_2043223       0.0
45018  061751_3374654_2043203       0.0

[45019 rows x 2 columns]

In [64]:
submission_df.loc[test_df_mask, "Expected"] = model.predict(test_df[NEW_PREDICTORS])
submission_df.loc[~test_df_mask, "Expected"] = 0
submission_df

                           Id    Expected
0      028631_3040064_2251003  216.954559
1      028631_3041214_2252063  215.189774
2      028631_3041184_2251693  257.339050
3      028631_3039864_2250783  218.816223
4      028631_3040224_2251483  239.833191
...                       ...         ...
45014  061751_3374644_2043173   49.675964
45015  061751_3374594_2043203   45.027897
45016  061751_3374624_2043173   87.220787
45017  061751_3374614_2043223  136.897537
45018  061751_3374654_2043203   70.820763

[45019 rows x 2 columns]

In [65]:
RESULT_CSV = f"{OUTPUT_PREFIX}/results_{MODEL_NAME}.csv"
submission_df.to_csv(RESULT_CSV, index=False)

MODEL_NAME

'XGB_v1_1787050491.38527'